spring:
 profiles:
  active: ES,prod
datasource:
 username: thanthu
 password: somespassword
 url: someurl

---
spring:
 profiles: prod
datasource:
 username: thanthu-prod
 password: somespassword-prod
 url: someurl-prod